### ISSUE TITLE
 can you realse the code  in the paper `End-to-End Model-Free Reinforcement Learning for Urban Driving using Implicit Affordances`

### ISSUE THREAD

**Issue by raozhongyu** [valeoai/rainbow-iqn-apex#3]
Thanks for your great work, can you realse the code  of the paper `End-to-End Model-Free Reinforcement Learning for Urban Driving using Implicit Affordances`. Thanks a lot

**Comment by HuPeng-Valer** [comment]
I noticed that iqn apex algorithm was used in the inference code you provided, but the code of auxiliary task mentioned in the paper is very important to me, and I also hope you can provide the code of training part. Thanks a lot!

**Comment by marintoro** [comment]
I have released the inference code in this [repo](https://github.com/valeoai/LearningByCheating).

**Comment by Kin-Zhang** [comment]
> I have released the inference code in this [repo](https://github.com/valeoai/LearningByCheating).

After I read the code, I found that for the reinforcement learning part, there is no code for that as well as no data generation from that.

**Comment by Kin-Zhang** [comment]
@marintoro  And I also found that I cannot send the email through the email on paper for communication.
Happy to find you here, and here is my email content:


Hi,

 

I’m a reader on your paper, and I want to ask some questions about it:

 

1. I found that you didn’t fully open source the code in RL on this paper said, even no dataset about the RL expert? As I try to find that how you get the RL expert and then find out there is no code or data about it.

2. In section 4.2, you said that desired rotation is because of previous two reward settings cannot act right when there is a static obstacle in front of the car, you want this rotation reward to explore more, but what’s the optimal trajectory? It’s still the lane waypoint angle? But in this way, you will still get the agent stuck at the lane? Since when they try to move, the rotation reward will be low as they departure the waypoint rotation

Is it Carla default nav agent to give you the optimal trajectory? -> but as you said at introduction, this one just stop at any obstacle, it will not try to do lane change.

 

Looking forward for your reply.

Have a good day.

 

Best wishes,

Kin (from HKUST)

**Comment by fatichii** [comment]
> @marintoro And I also found that I cannot send the email through the email on paper for communication. Happy to find you here, and here is my email content:
> 
> Hi,
> 
> I’m a reader on your paper, and I want to ask some questions about it:
> 
> 1. I found that you didn’t fully open source the code in RL on this paper said, even no dataset about the RL expert? As I try to find that how you get the RL expert and then find out there is no code or data about it.
> 2. In section 4.2, you said that desired rotation is because of previous two reward settings cannot act right when there is a static obstacle in front of the car, you want this rotation reward to explore more, but what’s the optimal trajectory? It’s still the lane waypoint angle? But in this way, you will still get the agent stuck at the lane? Since when they try to move, the rotation reward will be low as they departure the waypoint rotation
> 
> Is it Carla default nav agent to give you the optimal trajectory? -> but as you said at introduction, this one just stop at any obstacle, it will not try to do lane change.
> 
> Looking forward for your reply.
> 
> Have a good day.
> 
> Best wishes,
> 
> Kin (from HKUST)


@Kin-Zhang 
Hello dear Kin-Zhang! I found the same problem for this implementation,too. I just wanna know that did you find any solution for this issue or not?

Looking forward for your reply.

Have a good day.

Best wishes,

Zahra (from IUT university).

**Comment by fatichii** [comment]
@marintoro

Hello, I am a reader of your remarkable paper, "End-to-End Model-Free Reinforcement Learning for Urban Driving using Implicit Affordances." I am currently following the ReadMe instructions to run your implementation. However, I encountered an issue; I successfully ran the CARLA environment, but your code did not execute within the simulation. I received an error indicating that the RL part of the code is not accessible.

I would greatly appreciate your assistance in resolving this error, as it would be invaluable to my work. I intend to acknowledge your paper in my research.

I look forward to your reply.

Wishing you a wonderful day.

Best regards,

Zahra (from IUT University).

**Comment by xolovezari** [comment]
@marintoro
Hi 
I really interested in another amazing paper of yours, "GRI: General Reinforced Imitation and its Application to Vision-Based Autonomous Driving." 
Unfortunately, there is no implementation of that paper released. 
Can you help me by providing the code? I would greatly appreciate it; having the code would be immensely beneficial for my work. I intend to acknowledge your paper in my research.

I look forward to your reply.

Best regards,
Xolovezari
